### ISSUE TITLE
Future develope the patient views Preferred appointments times

### ISSUE THREAD

**Issue by Turtiainen** [Turtiainen/assisdent-web-client-continuation#22]
### **Description**
There are still problems though with the lists such as _Preferred appointment times_. 

The fetched patient data does not straight show everything right. 

Some values are just in the xml schema and current implementation does not have ready code for getting those values.

The current implementation of the parser need to be future developed.

### **DoD**

The parser is able to get values for lists for  _Preferred appointments times_.
The values in _Preferred appointments times_ are shown correctly. Numbers are mapped to correct dates and times.
The dropdown menus are not part of this story.

### **Picture from AssiDent client**

![Image](https://github.com/Turtiainen/assisdent-web-client-continuation/assets/120399613/3e00ec14-60ff-43d8-a355-daf1ee920d6f)

**Comment by Tommi98** [comment]
This issue has been completed to the point where the actual names are displayed from the schema's catalog.
