### ISSUE TITLE
Login page auth code to access token conversion

### ISSUE THREAD

**Issue by temp4ccount** [Turtiainen/assisdent-web-client-continuation#33]
**Description**

Currently the login page fetches an auth code from the API. This needs to be send back to the API to get a conversion for an access token. The access token is then used to sign-in into our web UI.

**DoD**

Fetching auth code, sending it to API and getting back an access token. Access token can in this stage be saved locally.

**Comment by BarryAlanPan** [comment]
The Oauth method used in ready made login page is outdated, even the api path don't exist anymore.

**Comment by BarryAlanPan** [comment]
Instead of OAuth, we need to replace into regular session log in, api method used in login page need to be rewrote.

**Comment by BarryAlanPan** [comment]
Old OAuth code are removed, login function is now using session API and input username/password to login, an error will be returned and displayed during login behaviour.
![CleanShot 2023-11-04 at 20 38 38@2x](https://github.com/Turtiainen/assisdent-web-client-continuation/assets/44538391/c9a2602c-3044-441a-974c-e34147cd59ef)
