### ISSUE TITLE
Login page redirect to web UI

### ISSUE THREAD

**Issue by temp4ccount** [Turtiainen/assisdent-web-client-continuation#34]
**Description**

Currently the login UI doesn't redirect anywhere after getting the auth code. In the mobile, where log in is used the embedded browser closes when client has the auth code. We need to redirect log in page into our web UI AFTER we have received the correct access token from API.

**DoD**

After fetching the access token from API, we should be redirected into our web UI (assuming the access token is valid and API approves it).

**Comment by BarryAlanPan** [comment]
```typescript
    if (!hasToken()) return <Login />;
    else
        return (
            <div className="App w-full flex relative">
                <Sidebar />
                <MainView>
                    ...
                </MainView>
            </div>
        );
```
Routing feature supported in modification of App.tsx. It can verify an existing logged in credential now.
