### ISSUE TITLE
Domain field does not work on login functionality

### ISSUE THREAD

**Issue by Turtiainen** [Turtiainen/assisdent-web-client-continuation#54]
**Description**

Currently the domain field does not work. It always uses the domain made for this project.

**DoD**
Make the domain selection dynamic.

**Comment by BarryAlanPan** [comment]
In current implementation, all api calling path are constants stored in [constants.ts](https://github.com/Turtiainen/assisdent-web-client-continuation/blob/181974266b123ea18f701601b11dd2e436e14a5f/src/utils/constants.ts), which means all api callings are limited to immutable url, a dynamic url calling function need to be implemented to fix the bug.
